# $Header: /home/cjm/cvs/libdprt-scs/Makefile.common,v 1.1 2025-02-11 11:20:21 cjm Exp $

SCS_HOME		= scs
LIBDPRT_SCS_SRC_HOME	= $(LIBDPRT_SRC_HOME)/$(SCS_HOME)
LIBDPRT_SCS_BIN_HOME	= $(LIBDPRT_BIN_HOME)/$(SCS_HOME)
LIBDPRT_SCS_DOC_HOME	= $(LIBDPRT_DOC_HOME)/$(SCS_HOME)

#
# $Log: not supported by cvs2svn $
#
